############################# 访问路径、端口tomcat start #############################
server:
  # 项目端口
  port: 9091
  # 内嵌Tomcat
  tomcat:
    # tomcat编码
    uri-encoding: UTF-8
    threads:
      # tomcat线程池大小设置
      max: 1000
      # tomcat初始化线程数量
      min-spare: 30
  servlet:
    # HTTP编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
############################# 访问路径、端口tomcat end ###############################

################################ spring config start ###############################
spring:
  application:
    # 应用程序名称
    name: dice
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  # 当前项目maven激活环境
  profiles:
    active: @profileActive@

# logback.xml中有详细的日志配置
logging:
  config: classpath:config/logback.xml
  #  方便Spring Boot Admin页面上实时查看日志
  file:
    name: logs/${spring.application.name}.log
################################ spring config end #################################

############################### mybatis-plus start #################################
mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.bihell.dice.blog.enums
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    # 全局默认主键类型
    db-config:
      id-type: auto
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
  # mapper xml映射路径
  mapper-locations: classpath:/mapper/*Mapper.xml
################################ mybatis-plus end ##################################

################################ dice start ########################################
dice:
  # 服务器IP地址
  server-ip: 127.0.0.1
################################ dice end ##########################################

############################## Spring boot admin start ##############################
---
spring:
  boot:
    admin:
      client:
        # Spring Boot Admin服务地址，参照admin模块application.yml配置
        url: http://${dice.server-ip}:8000
        # Spring Boot Admin账号
        username: admin
        # Spring Boot Admin密码
        password: admin
        # 当前项目实例名称
        instance:
          # client名称
          name: ${spring.application.name}
          # client ip端口
          service-base-url: http://${dice.server-ip}:${server.port}
      monitor:
        period: 100000
        status-lifetime: 100000
        connect-timeout: 100000
        read-timeout: 100000

# 开启和暴露端点
management:
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      #可在线查看日志
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
############################## Spring boot admin end ###############################

#################################### Swagger start #################################
---
dice:
  swagger:
    # 是否启用
    enable: true
    base:
      # 扫描的包，多个包使用逗号隔开
      package: com.bihell.dice,
    contact:
      email: tpxcer@outlook.com
      name: 胖哥
      url: https://bihell.com
    description: 个人管理系统API操作文档
    title: ${spring.application.name} API Documents
    url: https://github.com/bihell/Dice
    version: ${project.version}
    # 自定义参数配置，可配置N个
    parameter-config:
      - name: ${dice.jwt.token-name}
        description: Token Request Header
        # header, cookie, body, query
        type: header
        data-type: String
        required: false
        # 测试接口时，自动填充token的值
        default-value:

# knife4j配置
knife4j:
  enable: ${dice.swagger.enable}
  basic:
    enable: true
    username: admin
    password: admin

#################################### Swagger end ###################################
