#datasource
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.bihell.dice.mapper: trace
dice:
  doc-disabled: false
  auth-enabled: true

#################################### Swagger start #################################
---
dice:
  swagger:
    # 是否启用
    enable: true
    base:
      # 扫描的包，多个包使用逗号隔开
      package: com.bihell.dice,
    contact:
      email: tpxcer@outlook.com
      name: 胖哥
      url: https://bihell.com
    description: 个人管理系统API操作文档
    title: ${spring.application.name} API Documents
    url: https://github.com/bihell/Dice
    version: ${project.version}
    # 自定义参数配置，可配置N个
    parameter-config:
      - name: ${dice.jwt.token-name}
        description: Token Request Header
        # header, cookie, body, query
        type: header
        data-type: String
        required: false
        # 测试接口时，自动填充token的值
        default-value:

# knife4j配置
knife4j:
  enable: ${dice.swagger.enable}
  basic:
    enable: true
    username: admin
    password: admin

#################################### Swagger end ###################################
